# Usa una imagen base oficial de Python
FROM python:3.9-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de dependencias
COPY requirements.txt .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código de la aplicación
COPY . .

# Comando para ejecutar la aplicación usando Gunicorn (un servidor de producción)
# Cloud Run inyectará la variable de entorno PORT
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "main:app"]